input {
  file {
    path => "/var/log/app/app.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "application-logs"
  }

  stdout {
    codec => rubydebug
  }
}
